name: Latest stack oveflow activity
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://api.stackexchange.com/docs/collectives#order=desc&sort=name&filter=default&site=stackoverflow&run=true"
          template: "<tr><td>$title</td><td>$url</td></tr>"
